### createWorkshop

POST https://asia-east2-workshop-system-24df0.cloudfunctions.net/api/createWorkshop HTTP/1.1
content-type: application/json
authorization: {{$dotenv API_SECRET}}

{
  "title": "test",
  "description": "test",
  "venue": "test",
  "capacity": 120,
  "fee": 20,
  "duration": 60,
  "language": "eng",
  "datetime": "2022-09-16T14:30+0800"
}

### updateWorkshop

POST https://asia-east2-workshop-system-24df0.cloudfunctions.net/api/updateWorkshop HTTP/1.1
content-type: application/json
authorization: {{$dotenv API_SECRET}}

{
  "id": "mg7ljWUVPE9i2I6Z0tKW",
  "title": "test new"
}

### deleteWorkshop

POST https://asia-east2-workshop-system-24df0.cloudfunctions.net/api/deleteWorkshop HTTP/1.1
content-type: application/json
authorization: {{$dotenv API_SECRET}}

{
  "id": "mg7ljWUVPE9i2I6Z0tKW"
}

### initiateEnroll

POST https://asia-east2-workshop-system-24df0.cloudfunctions.net/api/initiateEnroll HTTP/1.1
content-type: application/json

{
  "workshopId": "nyX0QdsjSoChyFXPDZSe"
}

### enroll

POST https://asia-east2-workshop-system-24df0.cloudfunctions.net/api/enroll HTTP/1.1
content-type: application/json

{
  "workshopId": "nyX0QdsjSoChyFXPDZSe",
  "firstName": "test",
  "lastName": "test",
  "phone": "+85200000000",
  "email": "test@domain.com"
}

### createAdmin

POST https://asia-east2-workshop-system-24df0.cloudfunctions.net/api/createAdmin HTTP/1.1
content-type: application/json
authorization: {{$dotenv API_SECRET}}

{
  "phone": "+85296348097"
}

### deleteAdmin

POST https://asia-east2-workshop-system-24df0.cloudfunctions.net/api/deleteAdmin HTTP/1.1
content-type: application/json
authorization: {{$dotenv API_SECRET}}

{
  "phone": "+85296348097"
}