### createWorkshop

POST https://asia-east2-workshop-system-24df0.cloudfunctions.net/api/createWorkshop HTTP/1.1
content-type: application/json
authorization: {{$dotenv SECRET}}

{
  "title": "test",
  "description": "test",
  "venue": "test",
  "capacity": 120,
  "fee": 20,
  "duration": 60,
  "language": "eng",
  "datetimeStr": "2022-09-16T14:30+0800"
}

### createWorkshop

POST https://asia-east2-workshop-system-24df0.cloudfunctions.net/createWorkshop HTTP/1.1
content-type: application/json
authorization: {{$dotenv SECRET}}

{
  "title": "test",
  "description": "test",
  "venue": "test",
  "capacity": 120,
  "fee": 20,
  "duration": 60,
  "language": "eng",
  "datetimeStr": "2022-09-16T14:30+0800"
}

### updateWorkshop

POST https://asia-east2-workshop-system-24df0.cloudfunctions.net/updateWorkshop HTTP/1.1
content-type: application/json
authorization: {{$dotenv SECRET}}

{
  "id": "2DRgbvxaCBwBBMOTcp07",
  "title": "test new"
}

### deleteWorkshop

POST https://asia-east2-workshop-system-24df0.cloudfunctions.net/deleteWorkshop HTTP/1.1
content-type: application/json
authorization: {{$dotenv SECRET}}

{
  "id": "LI7ztvwGV9OPth3OMvuC"
}

### initiateEnroll

POST https://asia-east2-workshop-system-24df0.cloudfunctions.net/initiateEnroll HTTP/1.1
content-type: application/json

{
  "workshopId": "hyXOFX5xRcNXtfXmbedK"
}

### enroll

POST https://asia-east2-workshop-system-24df0.cloudfunctions.net/enroll HTTP/1.1
content-type: application/json

{
  "workshopId": "hyXOFX5xRcNXtfXmbedK",
  "enrollId": "046a1ced-96a3-433a-9243-638a584e855c",
  "firstName": "test",
  "lastName": "test",
  "phone": "+85200000000",
  "email": "test@domain.com"
}

### createAdmin

POST https://asia-east2-workshop-system-24df0.cloudfunctions.net/createAdmin HTTP/1.1
content-type: application/json
authorization: {{$dotenv SECRET}}

{
  "phone": "+85296348097"
}

### deleteAdmin

POST https://asia-east2-workshop-system-24df0.cloudfunctions.net/deleteAdmin HTTP/1.1
content-type: application/json
authorization: {{$dotenv SECRET}}

{
  "phone": "+85296348097"
}

### deleteEnrollSession

POST https://asia-east2-workshop-system-24df0.cloudfunctions.net/deleteEnrollSession HTTP/1.1
content-type: application/json

{
  "workshopId": "hyXOFX5xRcNXtfXmbedK",
  "enrollId": "046a1ced-96a3-433a-9243-638a584e855c"
}