### initiateEnroll

POST https://asia-east2-workshop-system-24df0.cloudfunctions.net/initiateEnroll HTTP/1.1
content-type: application/json

{
  "workshopId": "test",
}

### enroll

POST https://asia-east2-workshop-system-24df0.cloudfunctions.net/enroll HTTP/1.1
content-type: application/json

{
  "workshopId": "test",
  "enrollId": "test"
}

### makeAdmin

POST https://asia-east2-workshop-system-24df0.cloudfunctions.net/makeAdmin HTTP/1.1
content-type: application/json
authorization: {{$dotenv TEST_SECRET}}

{
  "phoneNumber": "+85296348097"
}

### deleteEnrollSession

POST https://asia-east2-workshop-system-24df0.cloudfunctions.net/deleteEnrollSession HTTP/1.1
content-type: application/json

{
  "workshopId": "test",
  "enrollId": "test"
}